Homework 4
ReneSung/CSharpHomework pull request #1
Opened 2024-09-23 13:41 UTC by ReneSung

2024-09-23 20:04 UTC, Dezodemius requested changes

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/Employee.cs
> +  internal abstract class Employee
дока

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/EmployeeManager.cs
> +    /// Колекция сотрудников.
Коллекция

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/EmployeeManager.cs
> +    public List<T> employees = new List<T>();
private

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/FullTimeEmployee.cs
> +  internal class FullTimeEmployee : Employee
дока

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/FullTimeEmployee.cs
> +
нужно убрать лишнюю строку

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/FullTimeEmployee.cs
> +	}
поехало куда-то

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/IEmployeeManager.cs
> +  /// <typeparam name="T">Объек Employee.</typeparam>
Объект

2024-09-23 20:04 UTC, Dezodemius commented on Homework4/EmployeeManager.cs
> +    public void Add(T employee)
коль метод это реализация интерфейса, то нужно его поместить в регион с именем этого интерфейса. И дока в таком случае не нужна

2024-09-24 10:42 UTC, ReneSung commented on Homework4/EmployeeManager.cs
> +    public void Add(T employee)
Исправлено

2024-09-24 10:42 UTC, ReneSung commented on Homework4/IEmployeeManager.cs
> +  /// <typeparam name="T">Объек Employee.</typeparam>
Исправлено

2024-09-24 10:42 UTC, ReneSung commented on Homework4/FullTimeEmployee.cs
> +	}
Исправлено

2024-09-24 10:42 UTC, ReneSung commented on Homework4/FullTimeEmployee.cs
> +
Исправлено

2024-09-24 10:42 UTC, ReneSung commented on Homework4/FullTimeEmployee.cs
> +  internal class FullTimeEmployee : Employee
Документация добавлена

2024-09-24 10:42 UTC, ReneSung commented on Homework4/EmployeeManager.cs
> +    public List<T> employees = new List<T>();
Исправлено

2024-09-24 10:43 UTC, ReneSung commented on Homework4/EmployeeManager.cs
> +    /// Колекция сотрудников.
Исправлено

2024-09-24 10:43 UTC, ReneSung commented on Homework4/Employee.cs
> +  internal abstract class Employee
Документация добавлена

2024-09-28 15:58 UTC, Dezodemius approved these changes

2024-09-29 08:07 UTC, merged