Домашнее задание 5
ReneSung/CSharpHomework pull request #2
Opened 2024-09-30 15:51 UTC by ReneSung

2024-09-30 19:21 UTC, Dezodemius requested changes

2024-09-30 19:21 UTC, Dezodemius commented on Homework5/UserAlreadyExistsException.cs
> +  /// Исключение, пользователь уже ссуществует.
опечатка

2024-09-30 19:21 UTC, Dezodemius commented on Homework5/UserManager.cs
> +        throw new UserAlreadyExistsException("Пользователь с таким id уже существует!");
можно указать с каким Id

2024-09-30 19:21 UTC, Dezodemius commented on Homework5/UserManager.cs
> +    public void ListUsers()
лучше это оставить Program. А метод переделать на метод, возвращающий список пользователей

2024-10-02 14:16 UTC, ReneSung commented on Homework5/UserManager.cs
> +    public void ListUsers()
Исправлено

2024-10-02 14:16 UTC, ReneSung commented on Homework5/UserManager.cs
> +        throw new UserAlreadyExistsException("Пользователь с таким id уже существует!");
сделано

2024-10-02 14:16 UTC, ReneSung commented on Homework5/UserAlreadyExistsException.cs
> +  /// Исключение, пользователь уже ссуществует.
исправлено

2024-10-03 05:48 UTC, Dezodemius approved these changes

2024-10-03 12:29 UTC, merged